### ISSUE TITLE
Check for duplicate stores/selectors dependencies in connect

### ISSUE THREAD

**Issue by rosenbergdev** [productboardlabs/tslint-pb#13]
I think it would be great and helpful if we could check for duplicates in the connect dependencies...

🙏 

<img width="316" alt="screenshot 2019-02-06 at 11 57 01" src="https://user-images.githubusercontent.com/12496597/52337164-2d9e5680-2a07-11e9-8cbb-9de73ec2d17a.png">

**Comment by jukben** [comment]
Great idea! I'll do it. 💪 Thanks!

**Comment by lspdv** [comment]
❤️😍
