### ISSUE TITLE
Fixer stopped working for the order of named imports

### ISSUE THREAD

**Issue by lspdv** [productboardlabs/tslint-pb#28]
In following example 

```
import {
  SubscriptionPlan,
  SubscriptionPlanInterval,
  SpaceMembership,
  User,
} from 'stores/types';
```

We get warning `Named imports are not sorted in alphabetical order`, only way how to get it fixed is manual solving, fixer doesnt work.

Observed for several times.

**Comment by jukben** [comment]
Thanks for it, I was able to reproduce it!
