### ISSUE TITLE
`canProcessNote` is falsely marked as a selector

### ISSUE THREAD

**Issue by opicacek** [productboardlabs/tslint-pb#41]
At the beginning of the file, selector is defined under alias:
```
import { canProcessNote as canProcessNoteSelector } from 'selectors/InboxSelectors';
```

In connect dependencies, we correctly list `canProcessNoteSelector` selector.

Issue:
`canProcessNote` is falsely marked by tslint as a selector.

https://github.com/productboard/pb-frontend/blob/master/src/js/modules/sidebar/components/note/NoteSidebarFooter.react.tsx#L141

**Comment by jukben** [comment]
🙏
