### ISSUE TITLE
When styles imported in file, the @productboard modules get sorted bellow styles

### ISSUE THREAD

**Issue by lspdv** [productboardlabs/tslint-pb#64]
I would expect styles imports will be always last as we are used to
![Screenshot 2019-10-22 at 10 19 39](https://user-images.githubusercontent.com/12471149/67268718-7d4d8100-f4b5-11e9-8307-5b4c65f2e02b.png)

**Comment by jukben** [comment]
We should be able to configure it via configuration https://github.com/productboardlabs/tslint-pb#configuration-1
